apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: fail
spec:
  steps:
  - name: pod-setup
    try:
    - create:
        file: pod.yaml
    - assert:
        file: verify-pod.yaml
  - name: deploy-setup
    try:
    - create:
        file: deploy.yaml
    - assert:
        file: verify-deploy.yaml