apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: fail
spec:
  steps:
  - name: pod-setup
    try:
    - create:
        file: pod.yaml
    - assert:
        file: "https://raw.githubusercontent.com/shubham-cmyk/chainsaw-demo/master/writing-test/Test-based-syntax/pass/verify-pod.yaml"
      timeout: 10s
  - name: deploy-setup
    try:
    - create:
        file: deploy.yaml
    - assert:
        file: verify-deploy.yaml
      timeout: 10s